import express from 'express';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createServer as createViteServer } from 'vite';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 3000;

const app = express();
app.use(express.json());

const SANDBOX_DIR = path.resolve(__dirname, '../sandbox-site');
const CONFIG_PATH = path.resolve(SANDBOX_DIR, 'theme.json');
const TARGET_CSS_PATH = path.resolve(SANDBOX_DIR, 'src/theme.css');

/**
 * Validates incoming theme configuration payloads against strict design system types.
 */
function validateConfig(config) {
  const hexRegex = /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/;
  const allowedModes = ['light', 'dark'];
  
  if (!allowedModes.includes(config.mode)) throw new Error('Invalid theme mode.');
  if (!hexRegex.test(config.accent)) throw new Error('Invalid hex color format for accent.');
  if (typeof config.radius !== 'string' || !config.radius.endsWith('px')) throw new Error('Invalid radius token format.');
  if (typeof config.fontBase !== 'string') throw new Error('Invalid font token format.');
  
  return {
    mode: config.mode,
    accent: config.accent,
    radius: config.radius,
    fontBase: config.fontBase
  };
}

/**
 * Compiles validated JSON tokens into an immutable, high-performance CSS custom properties layer.
 */
function compileTokensToCss(config) {
  const cssBuffer = `/**
 * @TODO - DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated dynamically by the LiteStyle Core Engine via theme.json.
 */
:root {
  color-scheme: ${config.mode};
  --ls-accent: ${config.accent};
  --ls-radius: ${config.radius};
  --ls-font-base: ${config.fontBase};

  /* Native CSS Semantic Light/Dark Adaptive Tokens */
  --ls-bg-main: light-dark(#ffffff, #0a0a0c);
  --ls-bg-surface: light-dark(#f8f9fa, #121216);
  --ls-text-main: light-dark(#111115, #f1f5f9);
  --ls-text-muted: light-dark(#64748b, #94a3b8);
  --ls-border: light-dark(#e2e8f0, #22222a);
}
`;
  fs.writeFileSync(TARGET_CSS_PATH, cssBuffer, 'utf-8');
}

// Internal Theme State Fetch API
app.get('/api/v1/config', (req, res) => {
  try {
    const rawData = fs.readFileSync(CONFIG_PATH, 'utf-8');
    res.status(200).json(JSON.parse(rawData));
  } catch (error) {
    res.status(500).json({ error: 'Failed to read design token state configuration.' });
  }
});

// Theme Mutator Compiler API
app.post('/api/v1/save-config', (req, res) => {
  try {
    const validatedData = validateConfig(req.body);
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(validatedData, null, 2), 'utf-8');
    compileTokensToCss(validatedData);
    res.status(200).json({ success: true, message: 'Tokens recompiled successfully.' });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// Initialize Vite HMR Development Server Middleware for Sandbox Application
const vite = await createViteServer({
  server: { middlewareMode: true, root: SANDBOX_DIR },
  appType: 'html'
});
app.use(vite.middlewares);

// Static Asset Allocation for Engine GUI Control Board
app.use('/dashboard', express.static(path.resolve(__dirname, 'dashboard.html')));

// Synchronize and generate initial stylesheet before runtime engine boots up
try {
  const initialTokens = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
  compileTokensToCss(initialTokens);
} catch (err) {
  console.error('⚠️ Critical: Initialization failed. Standard theme token fallback invoked.');
}

app.listen(PORT, () => {
  console.log('\n=============================================================');
  console.log('⚡ LIFESTYLE ENGINE ACTIVE');
  console.log(`Control Dashboard Board: http://localhost:${PORT}/dashboard`);
  console.log(`Live Sandbox Website:    http://localhost:${PORT}/index.html`);
  console.log('=============================================================\n');
});